import Layout from "@/layouts/default";
import TemplateLayout from "@/layouts/templateLayout";
import "@/styles/globals.css";
import { AppPropsWithLayout } from "@/types/NextPageWithLayout";
import Head from "next/head";
import { ReactNode } from "react";

export default function App({ Component, pageProps }: AppPropsWithLayout) {
  const getLayout = Component.getLayout ?? ((page) => page);

  return getLayout(
    <>
      <Head>
        <title>Learnly</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}
